enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# [YouTube]
# build-mode = "module"
# arch = "arm64-v8a"
# excluded-patches = "'Custom branding'"
# included-patches = ""
# version = "auto"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# # uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

# [Music]
# build-mode = "module"
# arch = "arm64-v8a"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# # uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[GooglePhotos]
enabled = false
build-mode = "module"
arch = "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
# uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[YouTube-Extended]
enabled = true
build-mode = "module"
arch = "arm64-v8a"
app-name = "YouTube"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube'"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Extended]
enabled = true
build-mode = "module"
arch = "arm64-v8a"
app-name = "YTMusic"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[YouTube-Extended-Anddea]
enabled = true
build-mode = "module"
arch = "arm64-v8a"
app-name = "YouTube"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube'"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"
rv-brand = "ReVanced Extended Anddea"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Extended-Anddea]
enabled = true
build-mode = "module"
arch = "arm64-v8a"
app-name = "YTMusic"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"
rv-brand = "ReVanced Extended Anddea"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"
